#!/bin/bash 
#SBATCH -J bwa_aln 
#SBATCH --output bwa_aln_%j.log  
#SBATCH --cpus-per-task=48   
#SBATCH --mem 140Gb  
#SBATCH -t 10-0  

module load BWA/0.7.17-GCC-10.2.0
module load SAMtools/1.16.1-GCC-11.2.0

GENOME=/project/stuckert/users/amdye/RADseq/R_imitator_striped_hifi.hic.1.0.fa

bwa index $GENOME

inds=$(basename -a /project/stuckert/users/amdye/RADseq/processed_reads/*.1.fq | grep -v "fastq.rem" | sed "s/.1.fq//g")

for sample in $inds
do
bwa aln -t 10 $GENOME /project/stuckert/users/amdye/RADseq/processed_reads/${sample}.1.fq > aligned_reads/${sample}.1.sai
bwa aln -t 10 $GENOME /project/stuckert/users/amdye/RADseq/processed_reads/${sample}.2.fq > aligned_reads/${sample}.2.sai
bwa sampe $GENOME aligned_reads/${sample}.1.sai aligned_reads/${sample}.2.sai /project/stuckert/users/amdye/RADseq/processed_reads/${sample}.1.fq /project/stuckert/users/amdye/RADseq/processed_reads/${sample}.2.fq > aligned_reads/sam_files/${sample}.sam
samtools view -bo aligned_reads/sam_files/${sample}.bam aligned_reads/sam_files/${sample}.sam
samtools sort aligned_reads/sam_files/${sample}.bam -o aligned_reads/sam_files/sorted_bam_files/${sample}.bam
done
